# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 96d5d2279c6c5d230e193898ff4dfe25a2ef434428ad7b0bafcb517c15e859577fc15929477410c44094c6386d869f8e94b1004df356951148aacbcfe744f609

test:
  secret_key_base: f675a279cb472f1c1eabe18e793d03a1f76f22355ddd204fa3283392b06e5e11885b0886758dbcefa9e03c054ee984e015cc7699a5a7c367e6ae98a6eeefaad5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
